# Generated by Django 3.2 on 2021-04-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_auto_20210430_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='cat', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='product_code',
            field=models.CharField(default='cat', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='unit_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
