# Generated by Django 3.2 on 2021-05-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_employeeinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
