# Generated by Django 3.2 on 2021-05-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_auto_20210515_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='order_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
