# Generated by Django 3.2 on 2021-05-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_history_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='unit_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
